apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-2ze1hp93syeldpcomc
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-scheduler: "wrr"
  labels:
    control-plane: controller-manager
  name: gin-web
  namespace: k8simagerolloutcontroller-system
spec:
  type: LoadBalancer
  ports:
    - port: 16100
      targetPort: 8082
      protocol: TCP
  selector:
    control-plane: controller-manager
